#!/usr/bin/env php
<?php
error_reporting(E_ALL);
ini_set('display_errors', true);

if (!ini_get('date.timezone')) {
    ini_set('date.timezone', 'UTC');
}

foreach ([
    __DIR__.'/../../autoload.php',
    __DIR__.'/../vendor/autoload.php',
    __DIR__.'/vendor/autoload.php'
    ] as $file) {

    if (file_exists($file)) {
        require $file;
        break;
    }
}

unset($file);

(new Schnittstabil\Sugared\Sami\Console\Application())->run();
